name: ribs_ip
version: 1.0.0-dev.4
homepage: https://cranst0n.github.io/ribs/
repository: https://github.com/cranst0n/ribs
description: >
  Typesafe representations for hosts, ports and addresses.

resolution: workspace
environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  punycoder:   ^0.2.2
  ribs_core:   ^1.0.0-dev.14
  ribs_effect: ^1.0.0-dev.3

dev_dependencies:
  lint:       ^2.8.0
  ribs_check: ^1.0.0-dev.8
  test:       ^1.0.0
