name: ribs_ip
version: 1.0.0-dev.3
homepage: https://cranst0n.github.io/ribs/
repository: https://github.com/cranst0n/ribs
description: >
  Typesafe representations for hosts, ports and addresses.

resolution: workspace
environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  ribs_core:   ^1.0.0-dev.12
  ribs_effect: ^1.0.0-dev.2

dev_dependencies:
  lint:       ^2.8.0
  ribs_check: ^1.0.0-dev.7
  test:       ^1.0.0
