name: ribs_check
version: 1.0.0-dev.7
homepage: https://cranst0n.github.io/ribs/
repository: https://github.com/cranst0n/ribs
description: >
  Property based testing.

resolution: workspace
environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  meta:      ^1.10.0
  ribs_core: ^1.0.0-dev.12
  test:      ^1.0.0

dev_dependencies:
  lint: ^2.8.0
