name: ribs_effect
version: 1.0.0-dev.2
homepage: https://cranst0n.github.io/ribs/
repository: https://github.com/cranst0n/ribs
description: >
  Provides effect types like IO, Ref and Resource.

resolution: workspace
environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  async:     ^2.13.0
  matcher:   ^0.12.17
  meta:      ^1.10.0
  ribs_core: ^1.0.0-dev.12
  test:      ^1.0.0

dev_dependencies:
  lint:       ^2.8.0
  ribs_check: ^1.0.0-dev.7
