name: ribs_binary
version: 1.0.0-dev.9
homepage: https://cranst0n.github.io/ribs/
repository: https://github.com/cranst0n/ribs
description: >
  Library provides fully typed binary parsing, encoding and decoding. Also
  supports streaming parsing.

resolution: workspace
environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  meta:      ^1.10.0
  ribs_core: ^1.0.0-dev.12

dev_dependencies:
  lint:       ^2.8.0
  ribs_check: ^1.0.0-dev.7
  test:       ^1.0.0
