name: ribs_units
version: 1.0.0-dev.10
homepage: https://cranst0n.github.io/ribs/
repository: https://github.com/cranst0n/ribs
description: >
  API for dimensional analysis.

resolution: workspace
environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  ribs_core:      ^1.0.0-dev.14

dev_dependencies:
  lint:       ^2.8.0
  ribs_check: ^1.0.0-dev.8
  test:       ^1.0.0
