name: ribs_bench
version: 0.0.1
homepage: https://cranst0n.github.io/ribs/
repository: https://github.com/cranst0n/ribs
description: >
  Various benchmarks.

publish_to: 'none'

resolution: workspace
environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  benchmark_harness:          ^2.3.1
  built_collection:           ^5.1.1
  chalk:                      ^1.2.1
  chalkdart:                  ^2.4.0
  cli_table:                  ^1.0.2
  dartz:                      ^0.10.1
  fast_immutable_collections: ^11.1.0
  fpdart:                     ^1.2.0
  kt_dart:                    ^1.1.0
  ribs_core:                  ^1.0.0-dev.12
  ribs_effect:                ^1.0.0-dev.2

dev_dependencies:
  lint: ^2.8.0
  test: ^1.0.0
