name: ribs_core
version: 1.0.0-dev.13
homepage: https://cranst0n.github.io/ribs/
repository: https://github.com/cranst0n/ribs
description: >
  Functional programming (FP) kernel. Provides common FP datatypes like
  Option, Either, State, Validated, as well as collection hierarchy
  inspired by the Scala programming language.

resolution: workspace
environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  async:   ^2.13.0
  matcher: ^0.12.17
  meta:    ^1.10.0
  test:    ^1.0.0

dev_dependencies:
  lint:       ^2.8.0
  ribs_check: ^1.0.0-dev.7
