name: snippets
description: Dart snippets used in website.
version: 1.0.0
publish_to: none

resolution: workspace
environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  async: ^2.13.0
  ribs_binary:
    path: ../../packages/binary/
  ribs_core:
    path: ../../packages/core/
  ribs_effect:
    path: ../../packages/effect/
  ribs_json:
    path: ../../packages/json/

dev_dependencies:
  lint: ^2.8.0
  test: ^1.0.0
